version: '3.5'

networks:
    
    micros:
        name: micros
        driver: overlay
    db:
        name: db
        driver: overlay

services:
    api:
        build:
            context: ./services/api
            args:
                NODE_ENV: development
        image: simple_arrow_api:dev
        ports:
            - 3000:3000
        command: npm run dev
        environment:
            NODE_ENV: development
            API_PORT: 3000
            RABBITMQ_URI: rabbitmq:5672
            RABBITMQ_USER: arrowadmin
            RABBITMQ_PASS: adminpassword
            RABBITMQ_VIRT_HOST: arrow_server
        volumes:
            - ./services/api:/app
        networks:
            - micros
        depends_on:
            - rabbitmq

    
    user:
        build:
            context: ./services/user
            args:
                NODE_ENV: development
        image: simple_arrow_user:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            RABBITMQ_URI: rabbitmq:5672
            RABBITMQ_USER: arrowadmin
            RABBITMQ_PASS: adminpassword
            RABBITMQ_VIRT_HOST: arrow_server
            MONGODB_HOST: mongodb
            MONGODB_PORT: 27017
            MONGODB_DB: arrow
        volumes:
            - ./services/user:/app
        networks:
            - micros
            - db
        depends_on:
            - mongodb
            - rabbitmq

    mongodb:
        image: mvertes/alpine-mongo
        ports:
            - 27017:27017
        volumes:
            - ./data/mongodb:/data/db
        networks:
            - db        

    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: rabbitmq
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq/
        ports:
            - 15672:15672
        secrets:
            - source: rabbitmq_conf
              target: /etc/rabbitmq/rabbitmq.conf
            - source: rabbitmq_plugins
              target: /etc/rabbitmq/enabled_plugins
        networks:
            - micros

secrets:
    rabbitmq_plugins:
        file: ./config/rabbitmq/enabled_plugins
    rabbitmq_conf:
        file: ./config/rabbitmq/rabbitmq.conf